---
title: "Gov 50 Final Project"
author: Shivali Korgaonkar
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to...

1. The breakdown of student's personal demographics (first generation/immigrant, international, home state, legacy status), and the relationship it had with them getting accepted/rejected from Harvard

2. The impact of anxiety, depression, or other mental health conditions on academic success

3. The association between women's pay and men's pay in the same sports, relative to viewership, sponsorship, advertisements, ticketing, and more.

## Milestone 2

Does a religious background make an LGBT individual less likely to come out? In this study, I will analyze how different religious backgrounds impact gay men, lesbians, bisexuals, and transgender individuals in coming out. I hypothesize that being religious makes people less comfortable coming out to family and friends. I expect that it is easier for people to come out when religion doesn’t play a big role in their life. My sample is composed of 1,197 survey results from gay men, lesbians, bisexuals, and transgender respondents who are 18 years or older. There is diversity in their religious backgrounds, as well as their status of discretion to the public on their sexuality and/or gender identity. The explanatory variable of interest is the religious status of the respondent, meaning their degree of religiousness, and if applicable, their religion. This is measured with two variables. First, =1 is Protestant, = 2 is Roman Catholic, =3 is Agnostic/Atheist, =4 is Nothing in Particular, =5 is Christian, and =6 is Other. Second, the importance of religion is measured as =1 is very important, =2 is somewhat important, =3 is not too important, and =4 is not at all important. The outcome variable is whether the important people in the individual’s life are aware of their sexuality and/or gender identity. The variable is measured as =1 means almost all know, =2 means some of them, =3 means a few, and =4 means none. The data comes from the KnowledgePanel research group in 2013. If the data shows that individuals with a low importance in religion have come out to almost all their loved ones, my hypothesis would be supported. If individuals with a heavy emphasis on religion come out at higher or equal levels as non-religious individuals, my hypothesis would be disproven. The additional variable of which religion they identify as can provide nuance in understanding which religions provide a more/less welcoming view towards the LGBT community coming out. When I run a regression on coming out status on non-religious individuals, a positive, significant coefficient would support my claim. 
